/*
 * Images: the `images` registry, the run's picture list, and a hero image on
 * the three records that had none.
 *
 * EVERY STATEMENT HERE IS IDEMPOTENT, AND THAT IS NOT THIS REPOSITORY'S
 * HABIT. Migrations are generated by `pnpm db:generate` and committed as
 * they come out. This one was edited by hand afterwards, and the reason is
 * written down here rather than left for the next person to reverse-engineer
 * out of a build log.
 *
 * This migration was first committed as `0010_images`. A push of that branch
 * built a Vercel preview, and `pnpm build` runs `pnpm db:migrate:deploy`, so
 * the whole of this file was applied to the Preview environment's database
 * and recorded in `drizzle.__drizzle_migrations` under that tag. Meanwhile
 * `0010_recipe_variants` landed on main and took the slot, so this file was
 * renumbered to `0011_images` and regenerated, which gave it a new
 * `when`. The next build therefore met a journal entry it had never applied
 * and a set of tables it had already created:
 *
 *     relation "experiment_images" already exists   (42P07)
 *
 * The objects are correct; only the name they were recorded under is gone.
 * Re-creating them is the only thing that fails, so each statement is
 * written to skip an object that is already there. That leaves this file
 * correct against an empty database and a no-op against the one that ran it
 * under the old name, which is what a migration in this state has to be.
 *
 * `pnpm db:generate` compares `src/db/schema.ts` against
 * `meta/0011_snapshot.json` and never rewrites an emitted `.sql`, so editing
 * this file does not move the `migration-drift` gate.
 */
CREATE TABLE IF NOT EXISTS "experiment_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"experiment_id" uuid NOT NULL,
	"position" integer NOT NULL,
	"image_url" text NOT NULL,
	"image_alt" text,
	"caption" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"blob_url" text NOT NULL,
	"blob_pathname" text NOT NULL,
	"mime_type" text NOT NULL,
	"alt" text NOT NULL,
	"caption" text,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"bytes" integer NOT NULL,
	"checksum" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" text,
	"deleted_reason" text,
	"deleted_event_id" uuid
);
--> statement-breakpoint
DROP VIEW IF EXISTS "public"."images_live";--> statement-breakpoint
DROP VIEW IF EXISTS "public"."experiments_live";--> statement-breakpoint
DROP VIEW IF EXISTS "public"."ingredients_live";--> statement-breakpoint
DROP VIEW IF EXISTS "public"."taxonomy_terms_live";--> statement-breakpoint
ALTER TABLE "experiments" ADD COLUMN IF NOT EXISTS "hero_image_url" text;--> statement-breakpoint
ALTER TABLE "experiments" ADD COLUMN IF NOT EXISTS "hero_image_alt" text;--> statement-breakpoint
ALTER TABLE "ingredients" ADD COLUMN IF NOT EXISTS "hero_image_url" text;--> statement-breakpoint
ALTER TABLE "ingredients" ADD COLUMN IF NOT EXISTS "hero_image_alt" text;--> statement-breakpoint
ALTER TABLE "taxonomy_terms" ADD COLUMN IF NOT EXISTS "hero_image_url" text;--> statement-breakpoint
ALTER TABLE "taxonomy_terms" ADD COLUMN IF NOT EXISTS "hero_image_alt" text;--> statement-breakpoint
/*
 * Postgres has no `ADD CONSTRAINT IF NOT EXISTS`, so the exception is caught
 * instead. This is the shape drizzle-kit itself emitted for foreign keys in
 * earlier versions, which is why it is the one used here rather than a
 * lookup against `pg_constraint`.
 */
DO $$ BEGIN
	ALTER TABLE "experiment_images" ADD CONSTRAINT "experiment_images_experiment_id_experiments_id_fk" FOREIGN KEY ("experiment_id") REFERENCES "public"."experiments"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_experiment_image_position" ON "experiment_images" USING btree ("experiment_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_experiment_images_experiment" ON "experiment_images" USING btree ("experiment_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_images_checksum" ON "images" USING btree ("checksum");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_images_deleted" ON "images" USING btree ("deleted_at" DESC NULLS LAST) WHERE "images"."deleted_at" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_images_deleted_event" ON "images" USING btree ("deleted_event_id") WHERE "images"."deleted_event_id" IS NOT NULL;--> statement-breakpoint
CREATE VIEW "public"."images_live" AS (select "id", "blob_url", "blob_pathname", "mime_type", "alt", "caption", "width", "height", "bytes", "checksum", "created_at", "updated_at", "deleted_at", "deleted_by", "deleted_reason", "deleted_event_id" from "images" where "images"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "public"."experiments_live" AS (select "id", "slug", "recipe_id", "revision_id", "title", "summary", "started_at", "completed_at", "scale_factor", "outcome", "cost_total", "currency", "hero_image_url", "hero_image_alt", "created_at", "updated_at", "deleted_at", "deleted_by", "deleted_reason", "deleted_event_id" from "experiments" where "experiments"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "public"."ingredients_live" AS (select "id", "slug", "name", "plural", "category", "description", "hero_image_url", "hero_image_alt", "density_g_per_ml", "default_unit", "aliases", "created_at", "updated_at", "deleted_at", "deleted_by", "deleted_reason", "deleted_event_id" from "ingredients" where "ingredients"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "public"."taxonomy_terms_live" AS (select "id", "facet", "slug", "label", "description", "hero_image_url", "hero_image_alt", "parent_id", "created_at", "updated_at", "deleted_at", "deleted_by", "deleted_reason", "deleted_event_id" from "taxonomy_terms" where "taxonomy_terms"."deleted_at" is null);
